# Generated by Django 2.0 on 2018-06-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0003_auto_20180622_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makechart.Employee'),
            preserve_default=False,
        ),
    ]
