# Generated by Django 2.0 on 2018-06-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0004_employee_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makechart.Employee'),
            preserve_default=False,
        ),
    ]
