# Generated by Django 2.0 on 2018-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0006_auto_20180624_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.CharField(default='Team Description Here', max_length=200),
            preserve_default=False,
        ),
    ]
