# Generated by Django 2.0 on 2018-07-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0009_auto_20180630_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='makechart.Employee'),
            preserve_default=False,
        ),
    ]
