# Generated by Django 2.0 on 2018-07-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0010_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='makechart.Employee'),
        ),
    ]
