# Generated by Django 2.0 on 2018-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0011_auto_20180630_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notemployees',
            field=models.ManyToManyField(related_name='notemployees', to='makechart.Employee'),
        ),
    ]
