# Generated by Django 2.0 on 2018-07-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0012_team_notemployees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='notemployees',
        ),
    ]
