# Generated by Django 2.0 on 2018-07-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0013_remove_team_notemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
