# Generated by Django 2.0.7 on 2018-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0015_auto_20180714_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='uploads/blank.png', upload_to='uploads/'),
        ),
    ]
